/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */

 

public class doktor extends javax.swing.JPanel {
private Statement stat;
private Connection Con;
private Connection con;
private ResultSet res;
private String t;
private Component rootPane;
int baris;
    

    public doktor(){
        initComponents();
        koneksi();
        tabel();
        buatkode();
    }
    
     private void koneksi(){
    try {
    Class.forName("com.mysql.jdbc.Driver");
    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/skripsiku", "root", "");
    stat=(Statement) con.createStatement();
    } catch (ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(null, e);
    }
    }
     
       private void kosongkan()
       { 
        kd_dokter.setText(""); 
       nama_dokter.setText("");
       cbsp.setSelectedItem("");
       cbjk.setSelectedItem("");
       telepon.setText("");
       email.setText("");
       alamat.setText("");
        }
       
       private void tabel(){ 
  DefaultTableModel t= new DefaultTableModel();
     t.addColumn("kd_dokter"); 
     t.addColumn("nama_dokter"); 
     t.addColumn("spesialis");
     t.addColumn("jenis_kelamin");
     t.addColumn("telepon");
     t.addColumn("email"); 
     t.addColumn("alamat"); 
     tabel_dokter.setModel(t); try{ res=stat.executeQuery("select * from dokter"); 
     while (res.next()) { 
     t.addRow(new Object[]{ res.getString("kd_dokter"),
     res.getString("nama_dokter"), 
     res.getString("spesialis"), 
     res.getString("jenis_kelamin"),
     res.getString("telepon"),
     res.getString("email"), 
     res.getString("alamat")
     }); 
     }
     }catch (Exception e) { 
     JOptionPane.showMessageDialog(rootPane, e); 
     } 
    }
private void buatkode(){
                  try {
    
String sql = "SELECT * FROM dokter ORDER BY kd_dokter DESC";


res=stat.executeQuery(sql);
if (res.next()) {
String kd_barang = res.getString("kd_dokter").substring(2);
String AN = "" +(Integer.parseInt(kd_barang) + 1);
String Nol = "";
if(AN.length()==1)
{Nol = "00";}
else if(AN.length()==2)
{Nol = "0";}
else if(AN.length()==3)
{Nol = "";}
kd_dokter.setText("D-"+ Nol +AN);
} else {
kd_dokter.setText("D-001");
}
} catch (Exception e) {
e.printStackTrace();
    
}
   } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kd_dokter = new javax.swing.JTextField();
        nama_dokter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_dokter = new javax.swing.JTable();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JToggleButton();
        btsimpan = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cbsp = new javax.swing.JComboBox();
        cbjk = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Belwe Bd BT", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FORM DOKTER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Dokter");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        kd_dokter.setEditable(false);
        add(kd_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 275, -1));
        add(nama_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 275, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Dokter");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Spesialis");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 275, -1));

        tabel_dokter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabel_dokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Pelanggan", "Nama Pelanggan", "Kontak", "Email", "Alamat"
            }
        ));
        tabel_dokter.setGridColor(new java.awt.Color(153, 153, 153));
        tabel_dokter.setSelectionBackground(new java.awt.Color(0, 153, 51));
        tabel_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dokterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_dokter);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 559, 210));

        btedit.setText("UBAH");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telepon");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 270, -1));
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 270, -1));

        cbsp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dokter Umum", "Dokter Gigi", "Kebidanan", "KB" }));
        add(cbsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        cbjk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki Laki", "Perempuan", " " }));
        add(cbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
         try {
            stat.executeUpdate("update dokter set "
                + "kd_dokter='"+kd_dokter.getText()+"',"
                + "nama_dokter='"+nama_dokter.getText()+"',"
              + "spesialis='"+cbsp.getSelectedItem()+"',"
                + "jenis_kelamin='"+cbjk.getSelectedItem()+"',"
                + "telepon='"+telepon.getText()+"',"
                + "email='"+email.getText()+"',"
                + "alamat='"+alamat.getText()+"'"
                + " where " + "kd_dokter='"+kd_dokter.getText()+"'" );
            kosongkan();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Di update");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
         tabel();
         buatkode();
        }    
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        try { 
        stat.executeUpdate("delete from dokter where " 
        + "kd_dokter='"+kd_dokter.getText()
        +"'" ); 
        JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (SQLException | HeadlessException e) { 
        JOptionPane.showMessageDialog(null, "pesan salah : "+e);
         } finally{
         tabel();
         buatkode();
          }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
   try {
 stat.executeUpdate("insert into dokter values (" 
+ "'" + kd_dokter.getText()+"',"
+ "'" + nama_dokter.getText()+"',"
+ "'" + cbsp.getSelectedItem()+"',"
+ "'" + cbjk.getSelectedItem()+"'," 
+ "'" + telepon.getText()+"'," 
+ "'" + email.getText()+"'," 
+ "'" + alamat.getText()+ "')");
kosongkan(); 
JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data"); 
} catch (SQLException | HeadlessException e) { 
JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
}finally{
         tabel();    
         buatkode();
 } 
    }//GEN-LAST:event_btsimpanActionPerformed

    private void tabel_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dokterMouseClicked
        baris = tabel_dokter.getSelectedRow();
        kd_dokter.setText(tabel_dokter.getValueAt(baris,0).toString());
        nama_dokter.setText(tabel_dokter.getValueAt(baris,1).toString());
        cbsp.setSelectedItem(tabel_dokter.getValueAt(baris,2).toString());
        cbjk.setSelectedItem(tabel_dokter.getValueAt(baris,3).toString());
        telepon.setText(tabel_dokter.getValueAt(baris,4).toString());
        email.setText(tabel_dokter.getValueAt(baris,5).toString());
        alamat.setText(tabel_dokter.getValueAt(baris,6).toString());
    }//GEN-LAST:event_tabel_dokterMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btedit;
    private javax.swing.JToggleButton bthapus;
    private javax.swing.JToggleButton btsimpan;
    private javax.swing.JComboBox cbjk;
    private javax.swing.JComboBox cbsp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_dokter;
    private javax.swing.JTextField nama_dokter;
    private javax.swing.JTable tabel_dokter;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables
}
   

