/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import javax.swing.JPanel;
import View.Dashboard;
import View.lapdiagnosa;
import View.lapobat;
import View.lappasien;
import View.laptransaksi;

/**
 *
 * @author User
 */
public class laporan extends javax.swing.JPanel {

    /**
     * Creates new form Barang
     */
    public laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pengembalian = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_keuntungan = new javax.swing.JButton();
        btn_LapPenjualan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pengembalian.setContentAreaFilled(false);
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });
        add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 100));

        btn_pembelian.setContentAreaFilled(false);
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 130, 110));

        btn_keuntungan.setContentAreaFilled(false);
        btn_keuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keuntunganActionPerformed(evt);
            }
        });
        add(btn_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 110, 110));

        btn_LapPenjualan.setContentAreaFilled(false);
        btn_LapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LapPenjualanActionPerformed(evt);
            }
        });
        add(btn_LapPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 160, 160));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Skripsiku\\src\\Image\\laporan.png")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        new lapdiagnosa().setVisible(true);
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
       new lappasien().setVisible(true);
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_keuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keuntunganActionPerformed
       new lapobat().setVisible(true);
    }//GEN-LAST:event_btn_keuntunganActionPerformed

    private void btn_LapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LapPenjualanActionPerformed
      new laptransaksi().setVisible(true);
    }//GEN-LAST:event_btn_LapPenjualanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LapPenjualan;
    private javax.swing.JButton btn_keuntungan;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
